# Generated by Django 3.1 on 2020-09-16 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rcapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bod', models.DateTimeField(verbose_name='Birth of Date')),
                ('address', models.CharField(max_length=20, verbose_name='Home Address')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('phone', models.IntegerField(verbose_name='Phone number')),
                ('created_at', models.DateTimeField(verbose_name='Date Created')),
                ('pic', models.ImageField(blank=True, upload_to=rcapp.models.user_directory_path, verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bod', models.DateTimeField(verbose_name='Birth of Date')),
                ('address', models.CharField(max_length=20, verbose_name='Home Address')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('phone', models.IntegerField(verbose_name='Phone number')),
                ('created_at', models.DateTimeField(verbose_name='Date Created')),
                ('pic', models.ImageField(blank=True, upload_to=rcapp.models.user_directory_path, verbose_name='Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Short description')),
                ('heart_rate', models.IntegerField(verbose_name='Heart rate value')),
                ('blood_pressure', models.IntegerField(verbose_name='Blood pressure vallue')),
                ('temperature', models.FloatField(verbose_name='Temperature value')),
                ('symptom', models.TextField(blank=True, verbose_name='symptoms')),
                ('image1', models.ImageField(upload_to=rcapp.models.user_directory_path)),
                ('image2', models.ImageField(upload_to=rcapp.models.user_directory_path)),
                ('image3', models.ImageField(upload_to=rcapp.models.user_directory_path)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('slot_duration', models.IntegerField(verbose_name='Duration of each slot')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Slot Start time')),
                ('end_time', models.DateTimeField(verbose_name='Slot End time')),
                ('video_link', models.URLField()),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.patient')),
                ('time_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=50, verbose_name='Medicine name')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('usage', models.CharField(max_length=150, verbose_name='Usage instruction')),
                ('patient_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.patientrecord')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.specialist'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
